site_name: LexSys Docs

pages:
- Home: index.md
- Escritorio: desk.md
- Portal: portal.md
- Editor: editor.md
- Instalación: instalacion.md
- FAQ: faq.md

theme: readthedocs
copyright: Tecno Informática Coproceso S.C.
